version: '3'
services:
  kali:
    build: .
    container_name: kali
    ports:
      - "5901:5901"
      - "7080:7080"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /workspace/template-palulu/shared:/root/shared